export type Lang = "ko" | "en";

export interface Skill {
  id: string;
  name: { ko: string; en: string };
  description: { ko: string; en: string };
  category: string;
  role: { ko: string; en: string };
  principles: { ko: string; en: string }[];
  processSteps: number;
  antiPatterns: { ko: string; en: string }[];
  lineCount: number;
  usageCount: number;
  path: string;
}

export interface Category {
  id: string;
  label: string;
  icon: string;
  description: { ko: string; en: string };
}

export const ui: Record<Lang, Record<string, string>> = {
  ko: {
    title: "Skill Book",
    subtitle_tpl: "{count} Skills · {steps} Process Steps · {lines} Lines of Knowledge",
    toc: "목차",
    all: "전체",
    roleTitle: "역할 정의",
    principlesTitle: "핵심 원칙",
    metricsTitle: "스킬 지표",
    antiTitle: "안티패턴",
    processSteps: "프로세스",
    principles: "원칙",
    lines: "라인",
    welcomeHeading: "Skill Book",
    welcomeDesc: "바이브코딩 시 AI가 자동으로 활용하는\n전문가 지식 라이브러리.\n\n왼쪽 목차에서 스킬을 선택하면\n이 페이지에서 상세 내용을 볼 수 있습니다.",
    footer: "Powered by Claude Code + bkit",
    skills: "skills",
    heroDesc: "Claude Code를 위한 전문가 스킬 컬렉션",
    installTitle: "설치하기",
    installDesc: "Claude Code에서 2줄이면 끝",
    step1Label: "마켓플레이스 등록",
    step1Cmd: "/plugin marketplace add sangjun0000/skillbook",
    step2Label: "플러그인 설치",
    step2Cmd: "/plugin install skillbook",
    step3Label: "스킬 사용",
    step3Cmd: "/skillbook:market-research",
    copied: "복사됨!",
    browseSkills: "스킬 둘러보기 ↓",
    howToUse: "사용 예시",
    used: "사용",
    totalUsed: "총 사용",
  },
  en: {
    title: "Skill Book",
    subtitle_tpl: "{count} Skills · {steps} Process Steps · {lines} Lines of Knowledge",
    toc: "Table of Contents",
    all: "All",
    roleTitle: "Role Definition",
    principlesTitle: "Core Principles",
    metricsTitle: "Skill Metrics",
    antiTitle: "Anti-Patterns",
    processSteps: "Process",
    principles: "Principles",
    lines: "Lines",
    welcomeHeading: "Skill Book",
    welcomeDesc: "An expert knowledge library\nautomatically used by AI during vibe coding.\n\nSelect a skill from the table of contents\nto view its details on this page.",
    footer: "Powered by Claude Code + bkit",
    skills: "skills",
    heroDesc: "A curated collection of expert skills for Claude Code",
    installTitle: "Install",
    installDesc: "Just 2 lines in Claude Code",
    step1Label: "Add marketplace",
    step1Cmd: "/plugin marketplace add sangjun0000/skillbook",
    step2Label: "Install plugin",
    step2Cmd: "/plugin install skillbook",
    step3Label: "Use skills",
    step3Cmd: "/skillbook:market-research",
    copied: "Copied!",
    browseSkills: "Browse Skills ↓",
    howToUse: "Usage Example",
    used: "Used",
    totalUsed: "Total Used",
  },
};

export const categories: Category[] = [
  { id: "business", label: "Business", icon: "📊", description: { ko: "시장조사, 경쟁 분석, SaaS 전략", en: "Market Research, Competitor Analysis, SaaS Strategy" } },
  { id: "ai", label: "AI / LLM", icon: "🤖", description: { ko: "프롬프트, 아키텍처, 에이전트", en: "Prompting, Architecture, Agents" } },
  { id: "dev", label: "Development", icon: "⚡", description: { ko: "API, 프론트엔드, DB, 웹 디자인", en: "API, Frontend, DB, Web Design" } },
  { id: "product", label: "Product", icon: "🎯", description: { ko: "UX 리서치, 제품 분석, 그로스", en: "UX Research, Analytics, Growth" } },
  { id: "meta", label: "Meta", icon: "📐", description: { ko: "스킬 생성 및 품질 관리", en: "Skill Creation & Quality" } },
  { id: "architecture", label: "Architecture", icon: "🏗️", description: { ko: "마이크로서비스, 이벤트 드리븐, 클린 아키텍처", en: "Microservices, Event-Driven, Clean Architecture" } },
  { id: "infra", label: "Infrastructure", icon: "☁️", description: { ko: "클라우드, 컨테이너, 모니터링, IaC", en: "Cloud, Containers, Monitoring, IaC" } },
  { id: "data", label: "Data", icon: "📈", description: { ko: "파이프라인, 시각화, SQL, 모델링", en: "Pipeline, Visualization, SQL, Modeling" } },
  { id: "mobile", label: "Mobile", icon: "📱", description: { ko: "React Native, 모바일 UX, 성능, 푸시 알림", en: "React Native, Mobile UX, Performance, Push" } },
  { id: "design", label: "Design", icon: "🎨", description: { ko: "디자인 시스템, 접근성, 인터랙션", en: "Design System, Accessibility, Interaction" } },
  { id: "legal", label: "Legal", icon: "⚖️", description: { ko: "개인정보보호, 오픈소스 라이선스, 약관, 계약 검토", en: "Privacy, OSS License, Terms of Service, Contract Review" } },
];

export const skills: Skill[] = [
  {
    id: "llm-architecture",
    name: { ko: "LLM 앱 아키텍처", en: "LLM App Architecture" },
    description: {
      ko: "프로덕션 레벨의 LLM 애플리케이션을 설계하고, 비용/성능/안정성을 최적화하는 전문 스킬",
      en: "A specialized skill for designing production-grade LLM applications and optimizing cost, performance, and reliability",
    },
    category: "ai",
    role: {
      ko: "당신은 LLM 기반 애플리케이션 아키텍처 분야의 시니어 전문가입니다. Next.js + FastAPI 스택에서 Claude/OpenAI API를 활용한 프로덕션 서비스를 다수 설계하고 운영한 경험을 보유하고 있습니다.",
      en: "You are a senior expert in LLM application architecture with extensive experience designing and operating production services using Claude/OpenAI APIs on Next.js + FastAPI stacks.",
    },
    principles: [
      { ko: "Streaming First: 사용자 체감 응답 시간을 줄이기 위해 항상 Streaming을 기본으로 설계한다", en: "Streaming First: Always design with streaming as default to reduce perceived response time" },
      { ko: "비용 최적화: 토큰 비용은 운영 비용의 핵심이다. 모델 선택, 캐싱, 프롬프트 압축으로 최적화한다", en: "Cost Optimization: Token cost is the core operating expense — optimize via model selection, caching, and prompt compression" },
      { ko: "Graceful Degradation: LLM API 장애 시에도 서비스가 완전히 중단되지 않도록 설계한다", en: "Graceful Degradation: Design so the service doesn't fully break during LLM API outages" },
      { ko: "관측 가능성: 모든 LLM 호출의 latency, token 사용량, 에러율을 추적한다", en: "Observability: Track latency, token usage, and error rates for every LLM call" },
      { ko: "확장 가능한 추상화: 모델 교체가 용이하도록 Provider 추상화 레이어를 설계한다", en: "Scalable Abstraction: Design a provider abstraction layer for easy model swapping" },
    ],
    processSteps: 19,
    antiPatterns: [
      { ko: "모든 작업에 최상위 모델 사용: 비용 10배 증가", en: "Using Top Model for Everything: 10x cost increase" },
      { ko: "Streaming 미적용: 빈 화면 10초 이상", en: "No Streaming: Blank screen for 10+ seconds" },
      { ko: "API Key 클라이언트 노출: 보안 위험", en: "Client-side API Key Exposure: Security risk" },
    ],
    lineCount: 203,
    usageCount: 5,
    path: "ai/llm-architecture.md",
  },
  {
    id: "web-visual-design",
    name: { ko: "웹 비주얼 디자인", en: "Web Visual Design" },
    description: {
      ko: "타이포그래피, 색상 체계, 공간 설계, 레이아웃 구성을 통해 시각적으로 완성도 높은 웹 페이지를 만드는 전문 스킬",
      en: "A specialized skill for creating visually polished web pages through typography, color systems, spacing, and layout composition",
    },
    category: "dev",
    role: {
      ko: "당신은 웹 비주얼 디자인 및 UI 미학의 시니어 전문가입니다. 디자이너 없이도 전문적인 시각 디자인을 구현할 수 있으며, 타이포그래피 시스템, 색상 이론, 공간 리듬, 시각적 계층 구조에 정통합니다.",
      en: "You are a senior web visual design and UI aesthetics expert who can implement professional visual design without a designer, with expertise in typography systems, color theory, spatial rhythm, and visual hierarchy.",
    },
    principles: [
      { ko: "시각적 계층(Visual Hierarchy): 크기, 무게, 색상, 공간으로 정보의 우선순위를 명확히 전달", en: "Visual Hierarchy: Communicate information priority clearly through size, weight, color, and space" },
      { ko: "일관된 공간 리듬(Spacing Rhythm): 4px/8px 기반 그리드로 모든 여백을 체계적으로 관리", en: "Spacing Rhythm: Manage all spacing systematically with a 4px/8px grid system" },
      { ko: "타이포그래피 스케일: clamp()를 활용한 유동적 폰트 크기 시스템으로 모든 화면에서 가독성 확보", en: "Typography Scale: Ensure readability on all screens with a fluid font size system using clamp()" },
      { ko: "색상 접근성: WCAG 2.1 AA 기준 명도 대비(4.5:1 이상), 색각 이상자를 고려한 색상 선택", en: "Color Accessibility: WCAG 2.1 AA contrast ratio (4.5:1+), color choices considering color blindness" },
      { ko: "의도적 여백(Whitespace): 빈 공간은 디자인 요소다 — 콘텐츠 밀도보다 호흡이 중요", en: "Intentional Whitespace: Empty space is a design element — breathing room matters more than density" },
      { ko: "Less is More: 꾸미는 요소를 추가하기보다, 기존 요소를 정제하여 완성도를 높임", en: "Less is More: Refine existing elements rather than adding decorative ones" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "색상 과다 사용: 5가지 이상의 강조 색상은 시각적 혼란 유발", en: "Color Overload: 5+ accent colors cause visual chaos" },
      { ko: "폰트 남용: 3가지 이상의 서체 조합은 통일감 훼손", en: "Font Abuse: 3+ typeface combinations break unity" },
      { ko: "마법 숫자 여백: 시스템에 없는 값 사용은 일관성 파괴", en: "Magic Number Spacing: Values outside the system break consistency" },
      { ko: "대비 부족: 연한 텍스트 on 밝은 배경은 읽기 어려움", en: "Low Contrast: Light text on light backgrounds is unreadable" },
    ],
    lineCount: 146,
    usageCount: 1,
    path: "dev/web-visual-design.md",
  },
  {
    id: "mcp-integration",
    name: { ko: "MCP 통합 전문가", en: "MCP Integration Expert" },
    description: {
      ko: "Model Context Protocol 서버/클라이언트 구현, 도구 정의, 리소스 관리, Claude Code 플러그인 개발",
      en: "MCP server/client implementation, tool definition, resource management, and Claude Code plugin development",
    },
    category: "ai",
    role: {
      ko: "당신은 MCP 통합 분야의 시니어 전문가입니다. TypeScript SDK를 활용한 MCP 서버 구현, 도구/리소스/프롬프트 정의, Claude Desktop 및 Claude Code 연동에 풍부한 실전 경험을 보유하고 있습니다.",
      en: "You are a senior MCP integration expert with extensive hands-on experience in MCP server implementation using TypeScript SDK, tool/resource/prompt definition, and Claude Desktop and Claude Code integration.",
    },
    principles: [
      { ko: "단일 책임 서버: 하나의 MCP 서버는 하나의 도메인에 집중", en: "Single Responsibility Server: One MCP server focuses on one domain" },
      { ko: "명확한 스키마 정의: 모든 도구의 inputSchema를 JSON Schema로 정확히 정의", en: "Explicit Schema Definition: Define all tool inputSchemas precisely with JSON Schema" },
      { ko: "안전한 도구 실행: 사용자 입력을 반드시 검증하고 부작용을 명시", en: "Safe Tool Execution: Always validate user input and declare side effects" },
      { ko: "Graceful 에러 처리: MCP 에러 코드를 준수하고 복구 가능한 메시지 반환", en: "Graceful Error Handling: Follow MCP error codes and return recoverable messages" },
      { ko: "Transport 독립성: 서버 로직을 Transport 계층과 분리", en: "Transport Agnostic: Separate server logic from transport layer" },
      { ko: "최소 권한 원칙: 서버가 접근하는 외부 리소스의 권한을 최소화", en: "Least Privilege: Minimize permissions for external resources the server accesses" },
    ],
    processSteps: 16,
    antiPatterns: [
      { ko: "모호한 도구 설명: description을 대충 작성하면 LLM이 잘못 선택", en: "Vague Tool Descriptions: Poorly written descriptions lead to wrong LLM selection" },
      { ko: "입력 검증 누락: 스키마만으로는 비즈니스 로직 검증 불가", en: "Missing Input Validation: Schema alone can't validate business logic" },
      { ko: "거대한 단일 서버: 하나의 서버에 모든 도구를 집중", en: "Monolithic Server: Putting all tools in a single server" },
      { ko: "에러 메시지에 내부 정보 노출: 스택 트레이스, DB 쿼리 노출", en: "Exposing Internal Info in Errors: Leaking stack traces and DB queries" },
      { ko: "Transport 의존적 코드: 서버 로직에 stdio/SSE 특정 코드를 혼합", en: "Transport-Dependent Code: Mixing stdio/SSE specific code in server logic" },
    ],
    lineCount: 178,
    usageCount: 2,
    path: "ai/mcp-integration.md",
  },
  {
    id: "sql-optimization",
    name: { ko: "SQL 고급 최적화 전문가", en: "SQL Optimization Expert" },
    description: {
      ko: "EXPLAIN ANALYZE 해석, 인덱스 전략, 윈도우 함수, CTE, 파티셔닝까지 PostgreSQL 쿼리 성능의 모든 측면을 최적화합니다.",
      en: "EXPLAIN ANALYZE 해석, 인덱스 전략, 윈도우 함수, CTE, 파티셔닝까지 PostgreSQL 쿼리 성능의 모든 측면을 최적화합니다.",
    },
    category: "data",
    role: {
      ko: "당신은 SQL 쿼리 최적화 및 PostgreSQL 성능 튜닝의 시니어 전문가입니다. 수십억 행 규모의 OLTP/OLAP 워크로드를 최적화한 경험이 풍부하며, 실행 계획 분석, 인덱스 설계(B-Tree/GIN/GiST/BRIN), 윈도우 함수 활용에 정통합니다. N+1 문제 해결, 파티셔닝 전략, 쿼리 리팩토링 경험을 갖추고 있습니다.",
      en: "당신은 SQL 쿼리 최적화 및 PostgreSQL 성능 튜닝의 시니어 전문가입니다. 수십억 행 규모의 OLTP/OLAP 워크로드를 최적화한 경험이 풍부하며, 실행 계획 분석, 인덱스 설계(B-Tree/GIN/GiST/BRIN), 윈도우 함수 활용에 정통합니다. N+1 문제 해결, 파티셔닝 전략, 쿼리 리팩토링 경험을 갖추고 있습니다.",
    },
    principles: [
      { ko: "**측정 후 최적화**: `EXPLAIN (ANALYZE, BUFFERS)`로 실행 계획을 확인한 후 병목 파악. 감으로 최적화 금지", en: "**측정 후 최적화**: `EXPLAIN (ANALYZE, BUFFERS)`로 실행 계획을 확인한 후 병목 파악. 감으로 최적화 금지" },
      { ko: "**인덱스는 읽기 패턴을 따른다**: WHERE, JOIN, ORDER BY 절 분석 후 인덱스 설계. 쓰기 오버헤드 고려", en: "**인덱스는 읽기 패턴을 따른다**: WHERE, JOIN, ORDER BY 절 분석 후 인덱스 설계. 쓰기 오버헤드 고려" },
      { ko: "**Seq Scan이 항상 나쁜 것은 아니다**: 소규모 테이블이나 대부분의 행을 읽는 경우 Sequential Scan이 더 빠를 수 있음", en: "**Seq Scan이 항상 나쁜 것은 아니다**: 소규모 테이블이나 대부분의 행을 읽는 경우 Sequential Scan이 더 빠를 수 있음" },
      { ko: "**복합 인덱스 컬럼 순서**: 선택도 높은 컬럼 앞 배치, 등호 조건 → 범위 조건 순서로 구성", en: "**복합 인덱스 컬럼 순서**: 선택도 높은 컬럼 앞 배치, 등호 조건 → 범위 조건 순서로 구성" },
      { ko: "**CTE 최적화 장벽 인지**: PostgreSQL 12+에서 CTE가 인라인되지만, `MATERIALIZED`로 강제 물리화 가능", en: "**CTE 최적화 장벽 인지**: PostgreSQL 12+에서 CTE가 인라인되지만, `MATERIALIZED`로 강제 물리화 가능" },
      { ko: "**윈도우 함수로 자기 조인 제거**: LAG/LEAD, ROW_NUMBER, SUM OVER로 서브쿼리와 자기 조인 대체", en: "**윈도우 함수로 자기 조인 제거**: LAG/LEAD, ROW_NUMBER, SUM OVER로 서브쿼리와 자기 조인 대체" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "**SELECT * 사용**: 불필요한 컬럼 I/O 증가. 필요한 컬럼만 명시", en: "**SELECT * 사용**: 불필요한 컬럼 I/O 증가. 필요한 컬럼만 명시" },
      { ko: "**OR 조건의 인덱스 무효화**: `WHERE a = 1 OR b > 2`는 인덱스 미사용. UNION ALL로 분리", en: "**OR 조건의 인덱스 무효화**: `WHERE a = 1 OR b > 2`는 인덱스 미사용. UNION ALL로 분리" },
      { ko: "**함수로 감싼 컬럼**: `WHERE LOWER(email) = ...`는 인덱스 무효화. Expression Index 또는 citext 사용", en: "**함수로 감싼 컬럼**: `WHERE LOWER(email) = ...`는 인덱스 무효화. Expression Index 또는 citext 사용" },
      { ko: "**OFFSET 딥 페이지네이션**: `OFFSET 100000`은 10만 행 스킵. Keyset Pagination(`WHERE id > last_id`)으로 대체", en: "**OFFSET 딥 페이지네이션**: `OFFSET 100000`은 10만 행 스킵. Keyset Pagination(`WHERE id > last_id`)으로 대체" },
      { ko: "**불필요한 DISTINCT**: JOIN 오류로 중복 발생 시 DISTINCT로 숨기지 말고 JOIN 조건 수정", en: "**불필요한 DISTINCT**: JOIN 오류로 중복 발생 시 DISTINCT로 숨기지 말고 JOIN 조건 수정" },
    ],
    lineCount: 177,
    usageCount: 1,
    path: "data/sql-optimization.md",
  },
  {
    id: "data-modeling",
    name: { ko: "데이터 모델링 전문가", en: "Data Modeling Expert" },
    description: {
      ko: "차원 모델링(Kimball), Star/Snowflake Schema, SCD, dbt 모델 레이어까지 분석용 데이터 모델의 전체 설계를 구축합니다.",
      en: "차원 모델링(Kimball), Star/Snowflake Schema, SCD, dbt 모델 레이어까지 분석용 데이터 모델의 전체 설계를 구축합니다.",
    },
    category: "data",
    role: {
      ko: "당신은 분석용 데이터 모델링 및 데이터 웨어하우스 설계의 시니어 전문가입니다. Kimball 방법론 기반의 차원 모델링으로 대규모 분석 시스템을 설계한 경험이 풍부하며, Fact/Dimension 테이블 설계, SCD 구현, Grain 정의에 정통합니다. dbt 모델 레이어링(staging/intermediate/marts)과 데이터 계약 관리 경험을 갖추고 있습니다.",
      en: "당신은 분석용 데이터 모델링 및 데이터 웨어하우스 설계의 시니어 전문가입니다. Kimball 방법론 기반의 차원 모델링으로 대규모 분석 시스템을 설계한 경험이 풍부하며, Fact/Dimension 테이블 설계, SCD 구현, Grain 정의에 정통합니다. dbt 모델 레이어링(staging/intermediate/marts)과 데이터 계약 관리 경험을 갖추고 있습니다.",
    },
    principles: [
      { ko: "**Grain을 먼저 정의**: Fact 테이블의 \"한 행 = 무엇\"을 먼저 명확히. Grain이 모호하면 모든 집계가 틀어짐", en: "**Grain을 먼저 정의**: Fact 테이블의 \"한 행 = 무엇\"을 먼저 명확히. Grain이 모호하면 모든 집계가 틀어짐" },
      { ko: "**Star Schema 우선**: Snowflake보다 Star Schema 기본 채택. JOIN 횟수 감소로 쿼리 성능과 이해도 향상", en: "**Star Schema 우선**: Snowflake보다 Star Schema 기본 채택. JOIN 횟수 감소로 쿼리 성능과 이해도 향상" },
      { ko: "**Conformed Dimensions**: 여러 Fact에서 공유하는 Dimension은 통일 정의. 부서별 \"고객\" 정의가 다르면 분석 오류", en: "**Conformed Dimensions**: 여러 Fact에서 공유하는 Dimension은 통일 정의. 부서별 \"고객\" 정의가 다르면 분석 오류" },
      { ko: "**SCD 타입은 비즈니스 기반 선택**: 이력 불필요 → Type 1(덮어쓰기), 변경 추적 → Type 2(새 행), 이전 값 보관 → Type 3(컬럼 추가)", en: "**SCD 타입은 비즈니스 기반 선택**: 이력 불필요 → Type 1(덮어쓰기), 변경 추적 → Type 2(새 행), 이전 값 보관 → Type 3(컬럼 추가)" },
      { ko: "**비정규화는 의도적으로**: 분석 모델의 비정규화는 전략적 선택. 운영 DB와 분리하여 관리", en: "**비정규화는 의도적으로**: 분석 모델의 비정규화는 전략적 선택. 운영 DB와 분리하여 관리" },
      { ko: "**dbt 레이어로 관심사 분리**: staging(소스 정제) → intermediate(비즈니스 로직) → marts(최종 모델)", en: "**dbt 레이어로 관심사 분리**: staging(소스 정제) → intermediate(비즈니스 로직) → marts(최종 모델)" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "**Grain 없는 Fact**: \"일단 넣어보자\"는 집계 오류의 원인. \"한 행 = 무엇\"을 먼저 결정", en: "**Grain 없는 Fact**: \"일단 넣어보자\"는 집계 오류의 원인. \"한 행 = 무엇\"을 먼저 결정" },
      { ko: "**Natural Key를 PK로**: 소스 ID 직접 사용 시 소스 변경 전파. Surrogate Key로 격리", en: "**Natural Key를 PK로**: 소스 ID 직접 사용 시 소스 변경 전파. Surrogate Key로 격리" },
      { ko: "**One Big Table 남용**: 모든 데이터를 하나의 Wide Table에 합치면 유지보수 불가", en: "**One Big Table 남용**: 모든 데이터를 하나의 Wide Table에 합치면 유지보수 불가" },
      { ko: "**Staging에 비즈니스 로직**: Staging은 rename/cast/filter만. 비즈니스 로직은 intermediate 이상", en: "**Staging에 비즈니스 로직**: Staging은 rename/cast/filter만. 비즈니스 로직은 intermediate 이상" },
      { ko: "**SCD Type 2 무조건 적용**: 변경 이력 불필요한 Dimension에 Type 2는 복잡성만 증가", en: "**SCD Type 2 무조건 적용**: 변경 이력 불필요한 Dimension에 Type 2는 복잡성만 증가" },
    ],
    lineCount: 174,
    usageCount: 0,
    path: "data/data-modeling.md",
  },
  {
    id: "react-native",
    name: { ko: "React Native 개발 전문가", en: "React Native Mobile Development Expert" },
    description: {
      ko: "Expo 워크플로우, React Navigation, 네이티브 모듈 연동, 플랫폼별 최적화를 활용한 크로스플랫폼 모바일 앱을 설계하고 구현합니다.",
      en: "Expo 워크플로우, React Navigation, 네이티브 모듈 연동, 플랫폼별 최적화를 활용한 크로스플랫폼 모바일 앱을 설계하고 구현합니다.",
    },
    category: "mobile",
    role: {
      ko: "당신은 React Native 크로스플랫폼 모바일 개발의 시니어 전문가입니다. Expo SDK와 Bare 워크플로우 모두에서 프로덕션 앱을 출시한 경험이 풍부하며, React Navigation 기반의 네비게이션 설계, 플랫폼별 UI 분기, Zustand/TanStack Query 상태 관리, NativeWind 스타일링, EAS Build/Submit 파이프라인 운영에 정통합니다.",
      en: "당신은 React Native 크로스플랫폼 모바일 개발의 시니어 전문가입니다. Expo SDK와 Bare 워크플로우 모두에서 프로덕션 앱을 출시한 경험이 풍부하며, React Navigation 기반의 네비게이션 설계, 플랫폼별 UI 분기, Zustand/TanStack Query 상태 관리, NativeWind 스타일링, EAS Build/Submit 파이프라인 운영에 정통합니다.",
    },
    principles: [
      { ko: "**Expo 우선 접근**: Expo SDK로 해결 가능한 기능은 Bare 워크플로우로 전환하지 않는다. `expo-dev-client` + Config Plugin 활용", en: "**Expo 우선 접근**: Expo SDK로 해결 가능한 기능은 Bare 워크플로우로 전환하지 않는다. `expo-dev-client` + Config Plugin 활용" },
      { ko: "**플랫폼 존중**: iOS HIG와 Material Design 각각의 관례를 따른다. `Platform.select`로 플랫폼별 최적 경험 제공", en: "**플랫폼 존중**: iOS HIG와 Material Design 각각의 관례를 따른다. `Platform.select`로 플랫폼별 최적 경험 제공" },
      { ko: "**네비게이션은 URL처럼**: Deep linking을 고려한 구조 설계. Expo Router의 파일 기반 라우팅 적극 활용", en: "**네비게이션은 URL처럼**: Deep linking을 고려한 구조 설계. Expo Router의 파일 기반 라우팅 적극 활용" },
      { ko: "**네이티브 성능 유지**: JS 스레드와 UI 스레드의 분리를 이해하고, 무거운 연산은 네이티브 측으로 위임", en: "**네이티브 성능 유지**: JS 스레드와 UI 스레드의 분리를 이해하고, 무거운 연산은 네이티브 측으로 위임" },
      { ko: "**오프라인 내성**: 네트워크 불안정을 전제로 설계. 로컬 캐싱과 낙관적 업데이트 기본 적용", en: "**오프라인 내성**: 네트워크 불안정을 전제로 설계. 로컬 캐싱과 낙관적 업데이트 기본 적용" },
      { ko: "**타입 안전성**: TypeScript strict mode, 네비게이션 파라미터 타입 정의, API 응답 타입 검증", en: "**타입 안전성**: TypeScript strict mode, 네비게이션 파라미터 타입 정의, API 응답 타입 검증" },
    ],
    processSteps: 15,
    antiPatterns: [
      { ko: "**성급한 Expo Eject**: 네이티브 모듈이 필요하다는 이유만으로 Bare 전환. `expo-dev-client` + Config Plugin으로 대부분 해결", en: "**성급한 Expo Eject**: 네이티브 모듈이 필요하다는 이유만으로 Bare 전환. `expo-dev-client` + Config Plugin으로 대부분 해결" },
      { ko: "**인라인 스타일 남용**: `style={{ margin: 10 }}`은 매 렌더링마다 새 객체 생성. `StyleSheet.create` 또는 NativeWind 사용", en: "**인라인 스타일 남용**: `style={{ margin: 10 }}`은 매 렌더링마다 새 객체 생성. `StyleSheet.create` 또는 NativeWind 사용" },
      { ko: "**네비게이션에 대량 데이터 전달**: 화면 간 전체 객체 대신 ID만 전달 후 해당 화면에서 조회", en: "**네비게이션에 대량 데이터 전달**: 화면 간 전체 객체 대신 ID만 전달 후 해당 화면에서 조회" },
      { ko: "**플랫폼 차이 무시**: iOS/Android의 뒤로가기, 제스처, 상태바 동작 차이를 고려하지 않은 설계", en: "**플랫폼 차이 무시**: iOS/Android의 뒤로가기, 제스처, 상태바 동작 차이를 고려하지 않은 설계" },
    ],
    lineCount: 220,
    usageCount: 3,
    path: "mobile/react-native.md",
  },
  {
    id: "app-performance",
    name: { ko: "앱 성능 최적화 전문가", en: "앱 성능 최적화 전문가" },
    description: {
      ko: "렌더링 최적화, 메모리 관리, 네트워크 효율화, 앱 시작 시간 단축, 프로파일링으로 모바일 앱의 체감 성능을 극대화합니다.",
      en: "렌더링 최적화, 메모리 관리, 네트워크 효율화, 앱 시작 시간 단축, 프로파일링으로 모바일 앱의 체감 성능을 극대화합니다.",
    },
    category: "mobile",
    role: {
      ko: "당신은 React Native 성능 최적화의 시니어 전문가입니다. JS 스레드와 UI 스레드의 동작 원리를 깊이 이해하고 있으며, FlatList 최적화, 메모이제이션 전략, 이미지 캐싱, 번들 크기 분석에 정통합니다. Flipper, React DevTools, Hermes 프로파일러를 활용한 병목 진단 경험이 풍부합니다.",
      en: "당신은 React Native 성능 최적화의 시니어 전문가입니다. JS 스레드와 UI 스레드의 동작 원리를 깊이 이해하고 있으며, FlatList 최적화, 메모이제이션 전략, 이미지 캐싱, 번들 크기 분석에 정통합니다. Flipper, React DevTools, Hermes 프로파일러를 활용한 병목 진단 경험이 풍부합니다.",
    },
    principles: [
      { ko: "**측정 먼저, 최적화 나중**: 프로파일링 데이터에 기반하여 최적화. 추측으로 코드를 복잡하게 만들지 않는다", en: "**측정 먼저, 최적화 나중**: 프로파일링 데이터에 기반하여 최적화. 추측으로 코드를 복잡하게 만들지 않는다" },
      { ko: "**60fps 사수**: UI 스레드 프레임 드롭 방지, 16ms 이내 렌더링. Reanimated로 JS 브릿지 우회", en: "**60fps 사수**: UI 스레드 프레임 드롭 방지, 16ms 이내 렌더링. Reanimated로 JS 브릿지 우회" },
      { ko: "**렌더링 최소화**: 불필요한 리렌더링 제거, 변경된 컴포넌트만 업데이트", en: "**렌더링 최소화**: 불필요한 리렌더링 제거, 변경된 컴포넌트만 업데이트" },
      { ko: "**메모리 누수 제로**: 언마운트 시 리스너/타이머/구독 반드시 정리", en: "**메모리 누수 제로**: 언마운트 시 리스너/타이머/구독 반드시 정리" },
      { ko: "**번들은 가볍게**: 미사용 코드 제거, 필요 시점에 로드(Lazy Loading)", en: "**번들은 가볍게**: 미사용 코드 제거, 필요 시점에 로드(Lazy Loading)" },
      { ko: "**네트워크 최소화**: 캐싱, 배치 요청, 증분 로딩으로 데이터 전송량 절감", en: "**네트워크 최소화**: 캐싱, 배치 요청, 증분 로딩으로 데이터 전송량 절감" },
      { ko: "**체감 성능 우선**: Skeleton UI와 낙관적 업데이트로 사용자가 느끼는 속도 개선", en: "**체감 성능 우선**: Skeleton UI와 낙관적 업데이트로 사용자가 느끼는 속도 개선" },
    ],
    processSteps: 6,
    antiPatterns: [
      { ko: "**성급한 최적화**: 프로파일링 없이 모든 컴포넌트에 `React.memo` 적용. 불필요한 메모이제이션은 메모리 낭비", en: "**성급한 최적화**: 프로파일링 없이 모든 컴포넌트에 `React.memo` 적용. 불필요한 메모이제이션은 메모리 낭비" },
      { ko: "**ScrollView로 긴 리스트**: 100+ 아이템을 ScrollView로 렌더링하면 전부 마운트. FlatList/FlashList 사용", en: "**ScrollView로 긴 리스트**: 100+ 아이템을 ScrollView로 렌더링하면 전부 마운트. FlatList/FlashList 사용" },
      { ko: "**인라인 객체/함수 전달**: `style={{ flex: 1 }}`이나 `onPress={() => handle()}`은 매번 새 참조 생성", en: "**인라인 객체/함수 전달**: `style={{ flex: 1 }}`이나 `onPress={() => handle()}`은 매번 새 참조 생성" },
      { ko: "**전역 상태 과다 구독**: Zustand 전체 구독 시 무관한 변경에도 리렌더링. selector로 필요한 값만 구독", en: "**전역 상태 과다 구독**: Zustand 전체 구독 시 무관한 변경에도 리렌더링. selector로 필요한 값만 구독" },
      { ko: "**이미지 원본 크기 전송**: 3000x4000 사진을 150x150으로 표시하면서 원본 다운로드. 서버 사이드 리사이징 필수", en: "**이미지 원본 크기 전송**: 3000x4000 사진을 150x150으로 표시하면서 원본 다운로드. 서버 사이드 리사이징 필수" },
    ],
    lineCount: 208,
    usageCount: 1,
    path: "mobile/app-performance.md",
  },
  {
    id: "accessibility",
    name: { ko: "웹 접근성 전문가", en: "Web Accessibility Expert" },
    description: {
      ko: "WCAG 2.2 AA 준수, 시맨틱 HTML, ARIA 패턴, 키보드 네비게이션, 스크린 리더 최적화, axe-core 자동화 테스트를 통해 모든 사용자가 동등하게 이용 가능한 웹을 구축하는 전문 스킬",
      en: "WCAG 2.2 AA 준수, 시맨틱 HTML, ARIA 패턴, 키보드 네비게이션, 스크린 리더 최적화, axe-core 자동화 테스트를 통해 모든 사용자가 동등하게 이용 가능한 웹을 구축하는 전문 스킬",
    },
    category: "design",
    role: {
      ko: "당신은 웹 접근성(a11y) 분야의 시니어 전문가입니다. WCAG 2.2 AA/AAA 기준에 정통하며, WAI-ARIA 역할/상태/속성 적용, 키보드 포커스 관리, 스크린 리더(VoiceOver, NVDA) 최적화, axe-core/jest-axe 자동화 테스트에 깊은 경험을 보유하고 있습니다.",
      en: "당신은 웹 접근성(a11y) 분야의 시니어 전문가입니다. WCAG 2.2 AA/AAA 기준에 정통하며, WAI-ARIA 역할/상태/속성 적용, 키보드 포커스 관리, 스크린 리더(VoiceOver, NVDA) 최적화, axe-core/jest-axe 자동화 테스트에 깊은 경험을 보유하고 있습니다.",
    },
    principles: [
      { ko: "**시맨틱 HTML 우선**: ARIA 추가 전에 네이티브 HTML 요소(`<button>`, `<nav>`, `<dialog>`)가 충분한지 검토", en: "**시맨틱 HTML 우선**: ARIA 추가 전에 네이티브 HTML 요소(`<button>`, `<nav>`, `<dialog>`)가 충분한지 검토" },
      { ko: "**키보드 완전 접근**: 모든 인터랙티브 요소는 Tab/Enter/Space/Escape/Arrow 키로 조작 가능해야 한다", en: "**키보드 완전 접근**: 모든 인터랙티브 요소는 Tab/Enter/Space/Escape/Arrow 키로 조작 가능해야 한다" },
      { ko: "**색상 대비 4.5:1**: 텍스트와 배경 간 최소 대비 비율을 항상 충족 (대형 텍스트 3:1)", en: "**색상 대비 4.5:1**: 텍스트와 배경 간 최소 대비 비율을 항상 충족 (대형 텍스트 3:1)" },
      { ko: "**포커스 가시성**: 포커스 인디케이터를 절대 제거하지 않으며, `:focus-visible`로 더 명확하게 표시", en: "**포커스 가시성**: 포커스 인디케이터를 절대 제거하지 않으며, `:focus-visible`로 더 명확하게 표시" },
      { ko: "**대체 텍스트 필수**: 정보를 전달하는 모든 비텍스트 콘텐츠에 적절한 alt 제공", en: "**대체 텍스트 필수**: 정보를 전달하는 모든 비텍스트 콘텐츠에 적절한 alt 제공" },
      { ko: "**동적 콘텐츠 알림**: 페이지 변경, 토스트, 에러는 ARIA Live Region으로 스크린 리더에 전달", en: "**동적 콘텐츠 알림**: 페이지 변경, 토스트, 에러는 ARIA Live Region으로 스크린 리더에 전달" },
    ],
    processSteps: 15,
    antiPatterns: [
      { ko: "**div/span 남용**: `<div onclick>` 대신 `<button>` 사용. div는 키보드 이벤트, 포커스, 역할 정보가 없다", en: "**div/span 남용**: `<div onclick>` 대신 `<button>` 사용. div는 키보드 이벤트, 포커스, 역할 정보가 없다" },
      { ko: "**outline: none 무조건 적용**: 포커스 인디케이터 제거는 키보드 사용자의 위치 파악을 불가능하게 한다", en: "**outline: none 무조건 적용**: 포커스 인디케이터 제거는 키보드 사용자의 위치 파악을 불가능하게 한다" },
      { ko: "**ARIA 과잉 사용**: `<button role=\"button\">`처럼 네이티브 HTML이 이미 역할을 가진 경우 중복 추가하지 않는다", en: "**ARIA 과잉 사용**: `<button role=\"button\">`처럼 네이티브 HTML이 이미 역할을 가진 경우 중복 추가하지 않는다" },
      { ko: "**색상만으로 상태 전달**: 에러를 빨간색만으로 표시하면 색각 이상자가 인지 불가. 아이콘/텍스트 항상 병행", en: "**색상만으로 상태 전달**: 에러를 빨간색만으로 표시하면 색각 이상자가 인지 불가. 아이콘/텍스트 항상 병행" },
      { ko: "**자동 재생 미디어**: 사전 동의 없는 오디오/비디오 자동 재생은 스크린 리더와 충돌한다", en: "**자동 재생 미디어**: 사전 동의 없는 오디오/비디오 자동 재생은 스크린 리더와 충돌한다" },
    ],
    lineCount: 180,
    usageCount: 1,
    path: "design/accessibility.md",
  },
  {
    id: "payment-billing",
    name: { ko: "결제·빌링 시스템 전문가", en: "Payment & Billing Architecture Expert" },
    description: {
      ko: "Stripe 기반 구독 결제 시스템 설계, webhook 멱등성, proration, dunning, PCI 스코프 최소화를 다루는 전문 스킬",
      en: "Expert skill for Stripe subscription billing, webhook idempotency, proration logic, dunning recovery, and PCI scope minimization",
    },
    category: "business",
    role: {
      ko: "당신은 SaaS 결제·빌링 시스템의 시니어 전문가입니다. Stripe, Paddle, Lemon Squeezy 등 결제 플랫폼을 활용한 구독 모델 설계 경험이 풍부하며, 결제 상태 머신, webhook 신뢰성, 세금 처리, PCI DSS 스코프 최소화에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in SaaS payment and billing systems with deep experience in Stripe, Paddle, and Lemon Squeezy subscription model design, payment state machines, webhook reliability, tax handling, and PCI DSS scope minimization.",
    },
    principles: [
      { ko: "구독 상태 머신 엄격 관리: trialing → active → past_due → canceled → expired 상태 전이를 명시적으로 정의하고 허용되지 않은 전이를 차단", en: "Strict Subscription State Machine: Explicitly define state transitions and block invalid transitions" },
      { ko: "Webhook 멱등성 필수: 모든 webhook 핸들러에 event.id 기반 중복 처리 로직 적용", en: "Webhook Idempotency: Apply event.id-based deduplication to all webhook handlers" },
      { ko: "PCI 스코프 최소화: 카드 정보를 서버에 절대 저장하지 않음, Stripe Elements/Checkout으로 PCI SAQ-A 유지", en: "PCI Scope Minimization: Never store card data on server, maintain PCI SAQ-A via Stripe Elements/Checkout" },
      { ko: "결제 실패는 정상 흐름: 카드 만료·한도 초과·분실은 예외가 아닌 정상 비즈니스 이벤트로 처리", en: "Payment Failure as Normal Flow: Treat card expiry, limit exceeded, and loss as normal business events" },
      { ko: "금액 계산은 정수(cents) 단위: 부동소수점 연산 금지, 모든 금액을 최소 통화 단위로 처리", en: "Integer Amount Calculation: No floating-point arithmetic, process all amounts in smallest currency unit (cents)" },
      { ko: "세금은 플랫폼 위임: Stripe Tax 등 전문 서비스에 위임하고 직접 계산하지 않음", en: "Delegate Tax Handling: Use Stripe Tax or TaxJar instead of custom tax calculation" },
      { ko: "감사 로그 의무화: 모든 결제 상태 변경, 요금제 변경, 환불에 immutable 감사 로그 기록", en: "Mandatory Audit Logging: Record immutable audit logs for all payment state changes, plan changes, and refunds" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "카드 번호 서버 저장: PCI DSS 위반 — 반드시 Stripe Elements/Checkout으로 토큰화", en: "Storing card numbers on server: PCI DSS violation — always tokenize via Stripe Elements/Checkout" },
      { ko: "Webhook 서명 미검증: 위조 이벤트 수신 가능 — constructEvent로 반드시 검증", en: "No webhook signature verification: Vulnerable to forged events — always verify with constructEvent" },
      { ko: "부동소수점 금액 계산: 0.1 + 0.2 ≠ 0.3 문제 — 항상 cents 정수 단위 사용", en: "Floating-point amount calculation: 0.1 + 0.2 ≠ 0.3 — always use integer cents" },
      { ko: "동기적 webhook 처리: 복잡한 로직을 핸들러 안에서 동기 실행 — 큐에 넣고 빠르게 200 응답", en: "Synchronous webhook processing: Running complex logic in handler — enqueue and respond 200 quickly" },
      { ko: "구독 상태 직접 업데이트: DB를 직접 수정 — Stripe를 Single Source of Truth로 사용", en: "Direct subscription state update: Modifying DB directly — use Stripe as Single Source of Truth" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "business/payment-billing.md",
  },
  {
    id: "multi-tenant",
    name: { ko: "멀티테넌트 아키텍처 전문가", en: "Multi-Tenant Architecture Expert" },
    description: {
      ko: "멀티테넌트 SaaS 격리 패턴 — RLS, 테넌트 격리(DB/schema/row), context propagation, 캐시 네임스페이싱, 크로스테넌트 데이터 누출 방지",
      en: "Multi-tenant SaaS isolation patterns — RLS, tenant isolation (DB/schema/row), context propagation, cache namespacing, cross-tenant data leak prevention",
    },
    category: "architecture",
    role: {
      ko: "당신은 멀티테넌트 SaaS 아키텍처의 시니어 전문가입니다. 수백~수천 테넌트를 서비스하는 B2B SaaS 시스템을 설계하고 운영한 경험이 풍부하며, 테넌트 격리 전략, RLS 구현, 테넌트 컨텍스트 전파, 캐시 네임스페이싱에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in multi-tenant SaaS architecture with deep experience serving hundreds to thousands of tenants in B2B SaaS systems, specializing in tenant isolation strategies, RLS implementation, tenant context propagation, and cache namespacing.",
    },
    principles: [
      { ko: "테넌트 격리는 기본값: 모든 데이터 접근 경로에 테넌트 필터가 적용되어야 함", en: "Tenant Isolation by Default: All data access paths must have tenant filters applied" },
      { ko: "RLS는 DB 레벨 강제: 애플리케이션 코드의 WHERE 절에만 의존하지 않고 PostgreSQL RLS 정책으로 강제", en: "RLS at DB Level: Enforce via PostgreSQL RLS policies, not just application-level WHERE clauses" },
      { ko: "테넌트 컨텍스트는 요청 전체에 전파: 미들웨어 → 서비스 → 리포지토리 → DB까지 자동 전파", en: "Tenant Context Propagation: Auto-propagate from middleware through service layer to DB queries" },
      { ko: "캐시 키에 테넌트 포함 필수: tenant:{id}: 접두사로 크로스테넌트 캐시 오염 방지", en: "Tenant in Cache Keys: Use tenant:{id}: prefix to prevent cross-tenant cache pollution" },
      { ko: "마이그레이션은 모든 테넌트에 원자적: 일부 테넌트에만 적용되는 상태를 허용하지 않음", en: "Atomic Migration Across Tenants: Never allow partial migration state across tenants" },
      { ko: "테넌트별 리소스 제한: Rate limiting, 스토리지 쿼터, API 호출 제한을 테넌트별로 적용", en: "Per-Tenant Resource Limits: Apply rate limiting, storage quotas, and API call limits per tenant" },
    ],
    processSteps: 15,
    antiPatterns: [
      { ko: "WHERE 절 의존: 한 곳이라도 빠지면 데이터 누출 — RLS로 DB 레벨 강제", en: "WHERE clause dependency: Missing one filter causes data leak — enforce via RLS at DB level" },
      { ko: "글로벌 캐시 키: 테넌트 구분 없는 캐시 키 — 크로스테넌트 데이터 오염", en: "Global cache keys: No tenant distinction — cross-tenant data pollution" },
      { ko: "하드코딩된 테넌트 식별: URL 파싱이나 하드코딩으로 판별 — 미들웨어에서 일관되게 처리", en: "Hardcoded tenant identification: URL parsing or hardcoding — handle consistently in middleware" },
      { ko: "공유 커넥션 풀에서 RLS 미설정: 이전 테넌트의 컨텍스트가 남을 수 있음", en: "No RLS in shared connection pool: Previous tenant context may persist" },
      { ko: "테넌트 삭제 시 데이터 잔류: DB·캐시·파일·큐에 데이터가 남는 상태", en: "Data retention on tenant deletion: Data remaining in DB, cache, files, and queues" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "architecture/multi-tenant.md",
  },
  {
    id: "background-jobs",
    name: { ko: "백그라운드 잡 전문가", en: "Background Jobs Architecture Expert" },
    description: {
      ko: "백그라운드 잡 처리 아키텍처 — BullMQ/Inngest 패턴, DLQ, graceful shutdown, 워커 동시성 제어, rate limiting, 잡 스케줄링",
      en: "Background job processing architecture — BullMQ/Inngest patterns, dead letter queues, graceful shutdown, worker concurrency, rate limiting, and job scheduling",
    },
    category: "dev",
    role: {
      ko: "당신은 백그라운드 잡 처리 시스템의 시니어 전문가입니다. BullMQ, Inngest, Temporal 등 큐 시스템을 활용한 비동기 처리 아키텍처를 설계하고 운영한 경험이 풍부하며, DLQ, graceful shutdown, 동시성 제어에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in background job processing systems with deep experience in BullMQ, Inngest, and Temporal queue architectures, specializing in DLQ, graceful shutdown, and concurrency control.",
    },
    principles: [
      { ko: "멱등성 필수: 모든 잡은 2회 이상 실행되어도 동일한 결과 보장 — at-least-once 전달 전제", en: "Mandatory Idempotency: All jobs must produce identical results on re-execution — design for at-least-once delivery" },
      { ko: "재시도 전략은 명시적: 최대 재시도 횟수, backoff 전략, 재시도 간격을 잡 정의 시 명시", en: "Explicit Retry Strategy: Define max retries, backoff strategy, and retry intervals in job definition" },
      { ko: "Dead Letter Queue 의무: 최대 재시도 후 실패 잡은 DLQ로 이동 — 자동 삭제 금지", en: "Mandatory DLQ: Move failed jobs to DLQ after max retries — no automatic deletion" },
      { ko: "Graceful Shutdown 보장: SIGTERM 시 현재 잡 완료 후 종료 — 잡 손실 방지", en: "Guaranteed Graceful Shutdown: Complete current jobs on SIGTERM before exit — prevent job loss" },
      { ko: "동시성 제어: 워커당 concurrency를 명시적으로 설정, 리소스에 따라 조정", en: "Concurrency Control: Explicitly set per-worker concurrency, adjust based on resources" },
      { ko: "잡 데이터 최소화: 큐 메시지에는 ID + 최소 메타데이터만, 전체 데이터는 DB에서 조회", en: "Minimize Job Data: Only ID + minimal metadata in queue messages, fetch full data from DB" },
      { ko: "타임아웃 설정 필수: 모든 잡에 최대 실행 시간 설정으로 무한 대기 방지", en: "Mandatory Timeout: Set max execution time for all jobs to prevent infinite waits" },
    ],
    processSteps: 15,
    antiPatterns: [
      { ko: "큐 메시지에 대용량 데이터: 파일 바이너리나 전체 레코드를 큐에 넣음 — ID만 사용", en: "Large data in queue messages: Putting file binaries or full records in queue — use IDs only" },
      { ko: "재시도 없는 워커: 일시적 오류에도 잡이 영구 실패 — exponential backoff 필수", en: "Worker without retries: Jobs fail permanently on transient errors — exponential backoff required" },
      { ko: "Graceful shutdown 미구현: kill -9로 강제 종료 — SIGTERM 핸들러 구현 필수", en: "No graceful shutdown: Force kill with kill -9 — must implement SIGTERM handler" },
      { ko: "무한 재시도: 재시도 횟수 제한 없이 영원히 재시도 — maxAttempts + DLQ 이동", en: "Infinite retries: Retrying forever without limit — set maxAttempts + move to DLQ" },
      { ko: "동기 처리 위장: API 핸들러에서 await longTask()로 동기 처리 — 큐에 넣고 즉시 응답", en: "Disguised sync processing: await longTask() in API handler — enqueue and respond immediately" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "dev/background-jobs.md",
  },
  {
    id: "search-engineering",
    name: { ko: "검색 엔지니어링 전문가", en: "Search Engineering Expert" },
    description: {
      ko: "검색 시스템 아키텍처 — Elasticsearch/Typesense 설정, 한국어 nori 분석기, 관련성 튜닝(BM25/boosting), 패싯 검색, 자동완성, 인덱싱 전략",
      en: "Search system architecture — Elasticsearch/Typesense setup, Korean nori analyzer, relevance tuning (BM25/boosting), faceted search, autocomplete, and indexing strategies",
    },
    category: "data",
    role: {
      ko: "당신은 검색 시스템 아키텍처의 시니어 전문가입니다. Elasticsearch, Typesense, Meilisearch 등 검색 엔진을 활용한 대규모 검색 시스템을 설계하고 운영한 경험이 풍부하며, 한국어 형태소 분석, 관련성 튜닝, 패싯 검색, 자동완성에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in search system architecture with deep experience in Elasticsearch, Typesense, and Meilisearch, specializing in Korean morphological analysis, relevance tuning, faceted search, and autocomplete.",
    },
    principles: [
      { ko: "검색은 DB 쿼리가 아니다: LIKE '%keyword%' 금지 — 전문 검색 엔진 사용 필수", en: "Search is Not a DB Query: No LIKE '%keyword%' — use dedicated search engines" },
      { ko: "인덱스 설계는 쿼리 패턴 기반: 사용자의 실제 검색 패턴 분석 후 매핑 설계", en: "Index Design by Query Pattern: Analyze actual search patterns before designing mappings" },
      { ko: "한국어 분석기 필수: 한국어 콘텐츠는 nori 분석기 적용 — standard 분석기 불가", en: "Korean Analyzer Required: Apply nori analyzer for Korean content — standard analyzer cannot handle Korean morphology" },
      { ko: "관련성은 데이터로 튜닝: 감이 아닌 CTR 데이터와 A/B 테스트 기반 조정", en: "Data-Driven Relevance Tuning: Adjust based on CTR data and A/B tests, not intuition" },
      { ko: "검색 결과 0건은 실패: 오타 교정, 동의어, 유사 결과 제공으로 해결", en: "Zero Results = Failure: Resolve with typo correction, synonyms, and similar results" },
      { ko: "인덱싱과 검색 분리: 쓰기와 읽기 워크로드를 분리하여 검색 성능 보호", en: "Separate Indexing and Search: Isolate write and read workloads to protect search performance" },
      { ko: "검색 품질 모니터링: 검색어별 CTR, 결과 없음 비율, 이탈률 추적", en: "Search Quality Monitoring: Track per-query CTR, zero-result rate, and bounce rate" },
    ],
    processSteps: 15,
    antiPatterns: [
      { ko: "LIKE '%keyword%' 검색: DB 풀스캔 유발, 형태소 분석 불가 — 전문 검색 엔진 사용", en: "LIKE '%keyword%' search: Causes full DB scan, no morphological analysis — use search engine" },
      { ko: "Standard 분석기로 한국어 처리: '삼성전자'를 하나의 토큰으로 인식", en: "Standard analyzer for Korean: Treats '삼성전자' as a single token" },
      { ko: "감 기반 boosting: title^10 등 임의 가중치 — CTR 데이터와 A/B 테스트로 조정", en: "Intuition-based boosting: Arbitrary weights like title^10 — adjust via CTR data and A/B tests" },
      { ko: "전체 재인덱싱만 지원: 변경 시 전체 인덱스 재생성 — 증분 업데이트 병행", en: "Full re-indexing only: Rebuilding entire index on changes — use incremental updates" },
      { ko: "검색 결과 0건 방치: '결과 없음'만 표시 — 오타 교정, 유사 검색어 제안", en: "Ignoring zero results: Only showing 'no results' — suggest typo corrections and similar queries" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "data/search-engineering.md",
  },
  {
    id: "email-delivery",
    name: { ko: "이메일 전송 아키텍처 전문가", en: "Email Delivery Architecture Expert" },
    description: {
      ko: "트랜잭션 이메일 아키텍처 — SPF/DKIM/DMARC 도메인 인증, 바운스 처리, 큐 분리, React Email/MJML 템플릿, 전송률 최적화",
      en: "Transactional email architecture — SPF/DKIM/DMARC domain authentication, bounce handling, queue separation, React Email/MJML templates, deliverability optimization",
    },
    category: "dev",
    role: {
      ko: "당신은 트랜잭션 이메일 전송 시스템의 시니어 전문가입니다. Resend, SendGrid, Postmark, AWS SES 등 ESP를 활용한 대규모 이메일 시스템 설계 경험이 풍부하며, 도메인 인증, 바운스 처리, 전송률 최적화, 이메일 템플릿 아키텍처에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in transactional email delivery systems with deep experience in Resend, SendGrid, Postmark, and AWS SES, specializing in domain authentication, bounce handling, deliverability optimization, and email template architecture.",
    },
    principles: [
      { ko: "도메인 인증 필수: SPF + DKIM + DMARC 세 가지 모두 설정 — 2024 Gmail/Yahoo 정책상 미인증 도메인은 스팸 처리", en: "Mandatory Domain Authentication: Configure SPF + DKIM + DMARC — unauthenticated domains are treated as spam per 2024 Gmail/Yahoo policy" },
      { ko: "큐 기반 비동기 전송: API 핸들러에서 직접 전송하지 않고 큐에 넣어 비동기 처리 — 실패 시 재시도 보장", en: "Queue-Based Async Sending: Never send directly from API handlers, enqueue for async processing — guarantees retry on failure" },
      { ko: "트랜잭션/마케팅 분리: 트랜잭션 이메일과 마케팅 이메일을 별도 큐·IP·발신 도메인으로 분리 — 마케팅 스팸 신고가 트랜잭션 전송률에 영향 주지 않도록", en: "Separate Transactional/Marketing: Isolate queues, IPs, and sending domains — prevent marketing spam reports from affecting transactional deliverability" },
      { ko: "바운스는 정상 흐름: 하드 바운스(즉시 차단), 소프트 바운스(N회 재시도 후 차단), 컴플레인(즉시 차단) — 예외가 아닌 비즈니스 이벤트로 처리", en: "Bounces Are Normal Flow: Hard bounce (block immediately), soft bounce (retry N times then block), complaint (block immediately) — treat as business events" },
      { ko: "템플릿 시스템 사용: React Email 또는 MJML로 반응형 이메일 작성 — raw HTML 문자열 직접 작성 금지", en: "Use Template System: Build responsive emails with React Email or MJML — never write raw HTML strings" },
      { ko: "전송률 모니터링: 바운스율, 스팸 신고율, 오픈율, 클릭율을 지표로 추적 — 바운스율 2% 이상이면 긴급 대응", en: "Deliverability Monitoring: Track bounce rate, spam complaint rate, open rate, click rate — bounce rate above 2% requires urgent action" },
      { ko: "IP 워밍업 필수: 새 IP/도메인은 소량부터 시작하여 2-4주에 걸쳐 점진적으로 볼륨 증가 — 갑작스러운 대량 발송은 스팸 판정", en: "IP Warm-up Required: Start with low volume on new IP/domain and gradually increase over 2-4 weeks — sudden high volume triggers spam classification" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "API 핸들러 내 동기 전송: sendEmail()을 await로 직접 호출 — 큐에 넣고 즉시 응답", en: "Synchronous sending in API handler: Directly awaiting sendEmail() — enqueue and respond immediately" },
      { ko: "도메인 인증 미설정: SPF/DKIM/DMARC 없이 발송 — 높은 확률로 스팸함 도착", en: "No domain authentication: Sending without SPF/DKIM/DMARC — high probability of landing in spam" },
      { ko: "바운스 무시: 반복 바운스 주소에 계속 발송 — ISP가 발신 도메인을 차단", en: "Ignoring bounces: Continuing to send to repeatedly bouncing addresses — ISP blocks sending domain" },
      { ko: "raw HTML 이메일: 인라인 스타일 없는 HTML 직접 작성 — Outlook에서 깨짐, 반응형 불가", en: "Raw HTML emails: Writing HTML without inline styles — breaks in Outlook, no responsiveness" },
      { ko: "트랜잭션/마케팅 혼합: 동일 IP로 모든 이메일 발송 — 마케팅 스팸 신고가 비밀번호 재설정 전송률까지 하락시킴", en: "Mixing transactional/marketing: Sending all emails from same IP — marketing complaints degrade password reset deliverability" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "dev/email-delivery.md",
  },
  {
    id: "file-upload",
    name: { ko: "파일 업로드 아키텍처 전문가", en: "File Upload & Storage Architecture Expert" },
    description: {
      ko: "파일 업로드·저장 아키텍처 — S3/R2 presigned URL 직접 업로드, multipart 업로드, 이미지 프로세싱 파이프라인, CORS 설정, 콘텐츠 검증, CDN 서빙",
      en: "File upload and storage architecture — S3/R2 presigned URLs, multipart upload, image processing pipeline, CORS configuration, content validation, and CDN serving",
    },
    category: "dev",
    role: {
      ko: "당신은 파일 업로드·저장 시스템의 시니어 전문가입니다. S3/R2/GCS 기반 대규모 파일 처리 시스템을 설계하고 운영한 경험이 풍부하며, presigned URL 패턴, multipart 업로드, 이미지 프로세싱 파이프라인, CDN 서빙에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in file upload and storage systems with deep experience in S3/R2/GCS large-scale file processing, specializing in presigned URL patterns, multipart upload, image processing pipelines, and CDN serving.",
    },
    principles: [
      { ko: "서버 경유 금지: 클라이언트가 presigned URL로 S3/R2에 직접 업로드 — 서버에 파일 바이너리를 스트리밍하지 않음", en: "No Server Passthrough: Client uploads directly to S3/R2 via presigned URL — never stream file binaries through the server" },
      { ko: "대용량은 Multipart: 100MB 이상 파일은 반드시 multipart upload — 단일 PUT은 타임아웃과 재시도 불가 유발", en: "Multipart for Large Files: Files over 100MB must use multipart upload — single PUT causes timeouts and no retry capability" },
      { ko: "업로드 후 처리: 원본 저장 → 이벤트 트리거 → Lambda/Worker에서 리사이즈·최적화 — 업로드 시점에 동기 처리 금지", en: "Post-Upload Processing: Store original → event trigger → resize/optimize in Lambda/Worker — no synchronous processing at upload time" },
      { ko: "콘텐츠 검증 이중화: presigned URL 정책 조건(content-type, content-length-range)으로 1차, 서버에서 magic bytes 검증으로 2차", en: "Dual Content Validation: Presigned URL policy conditions (content-type, content-length-range) as 1st layer, server-side magic bytes verification as 2nd" },
      { ko: "CDN 경유 서빙: 파일 제공은 반드시 CDN(CloudFront/R2 custom domain) 경유 — S3 직접 접근 URL 노출 금지", en: "CDN-Only Serving: Always serve files through CDN (CloudFront/R2 custom domain) — never expose direct S3 access URLs" },
      { ko: "CORS ETag 노출 필수: multipart upload 시 브라우저가 ETag 헤더를 읽을 수 있도록 ExposeHeaders 설정 필수", en: "CORS ETag Exposure Required: Configure ExposeHeaders for ETag — browsers block multipart completion without it" },
      { ko: "스토리지 라이프사이클: 임시 업로드 30일 후 자동 삭제, 완료된 파일만 영구 버킷으로 이동", en: "Storage Lifecycle: Auto-delete temp uploads after 30 days, move only completed files to permanent bucket" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "서버 경유 업로드: multer로 서버에 파일을 받아 S3로 재전송 — 서버 메모리/CPU 낭비, 타임아웃 위험", en: "Server passthrough upload: Receiving files via multer then re-uploading to S3 — wastes server memory/CPU, timeout risk" },
      { ko: "단일 PUT 대용량: 수백 MB 파일을 하나의 PUT 요청으로 전송 — 네트워크 오류 시 처음부터 재시작", en: "Single PUT for large files: Sending hundreds of MB in one PUT request — restart from beginning on network error" },
      { ko: "ETag 미노출 CORS: multipart upload에서 CORS ExposeHeaders에 ETag 누락 — 브라우저가 완료 요청 차단", en: "Missing ETag in CORS: Omitting ETag from CORS ExposeHeaders in multipart upload — browser blocks completion request" },
      { ko: "동기 이미지 처리: 업로드 API 핸들러에서 Sharp 리사이즈 동기 실행 — 응답 지연, 타임아웃", en: "Synchronous image processing: Running Sharp resize in upload API handler — response delay, timeout" },
      { ko: "S3 URL 직접 노출: presigned GET URL을 프론트엔드에 영구 저장 — 만료 후 깨짐, 보안 위험", en: "Exposing direct S3 URLs: Storing presigned GET URLs permanently in frontend — breaks after expiry, security risk" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "dev/file-upload.md",
  },
  {
    id: "caching-strategy",
    name: { ko: "캐싱 전략 전문가", en: "Caching Strategy Expert" },
    description: {
      ko: "애플리케이션 캐싱 아키텍처 — Next.js 15 캐시 레이어(Request Memoization, Data Cache, Full Route Cache, Router Cache), Redis 패턴, 태그 기반 무효화, CDN 상호작용, 캐시 키 설계",
      en: "Application caching architecture — Next.js 15 cache layers (Request Memoization, Data Cache, Full Route Cache, Router Cache), Redis patterns, tag-based invalidation, CDN interaction, cache key design",
    },
    category: "dev",
    role: {
      ko: "당신은 애플리케이션 캐싱 아키텍처의 시니어 전문가입니다. Next.js 15 캐시 모델, Redis 캐시 핸들러, CDN 엣지 캐싱, 캐시 무효화 전략을 깊이 이해하고, 프로덕션 환경에서 캐시 관련 버그를 예방하는 데 특화되어 있습니다.",
      en: "You are a senior expert in application caching architecture with deep understanding of Next.js 15 cache model, Redis cache handlers, CDN edge caching, and cache invalidation strategies, specializing in preventing cache-related bugs in production.",
    },
    principles: [
      { ko: "Next.js 15는 opt-in 캐시: fetch()가 기본적으로 캐시되지 않음 (Next 14와 반대) — force-cache 또는 revalidate 명시 필요", en: "Next.js 15 Opt-In Cache: fetch() is NOT cached by default (opposite of Next 14) — must explicitly set force-cache or revalidate" },
      { ko: "4-Layer 캐시 모델 이해: Request Memoization → Data Cache → Full Route Cache → Router Cache 각 레이어의 역할과 무효화 방식을 구분", en: "Understand 4-Layer Cache Model: Request Memoization → Data Cache → Full Route Cache → Router Cache — distinguish each layer's role and invalidation" },
      { ko: "태그 기반 무효화: 뮤테이션 시 revalidateTag()로 관련 캐시만 정밀 무효화 — revalidatePath('/')로 전체 무효화하지 않음", en: "Tag-Based Invalidation: Use revalidateTag() for surgical invalidation on mutation — never revalidatePath('/') for full invalidation" },
      { ko: "멀티 인스턴스는 Redis: 컨테이너/서버리스 환경에서 파일시스템 캐시는 split-brain 유발 — Redis 캐시 핸들러 필수", en: "Redis for Multi-Instance: File system cache causes split-brain in container/serverless — Redis cache handler required" },
      { ko: "캐시 키에 컨텍스트 포함: tenant ID, locale, API version을 키에 포함 — bare entity ID만 사용 시 크로스테넌트 오염", en: "Context in Cache Keys: Include tenant ID, locale, API version in keys — bare entity IDs cause cross-tenant pollution" },
      { ko: "CDN 헤더와 ISR 충돌 방지: s-maxage와 revalidate 동시 설정 시 충돌 — ISR 사용 시 CDN은 stale-while-revalidate로", en: "Prevent CDN-ISR Conflicts: s-maxage and revalidate conflict when set together — use stale-while-revalidate with ISR" },
      { ko: "캐시 히트율 모니터링: 캐시를 추가하면 반드시 히트율을 측정 — 히트율 80% 미만이면 키 설계 또는 TTL 재검토", en: "Monitor Cache Hit Rate: Always measure hit rate after adding cache — review key design or TTL if hit rate below 80%" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "Next.js 14 캐시 가정: fetch()가 자동으로 캐시된다고 가정 — Next 15부터는 명시적 opt-in 필요", en: "Assuming Next.js 14 caching: Assuming fetch() is automatically cached — Next 15 requires explicit opt-in" },
      { ko: "단순 TTL만 사용: 모든 캐시에 동일한 TTL 적용 — 데이터 특성에 따라 차등 TTL + 태그 기반 무효화 병행", en: "TTL-only caching: Applying same TTL to all caches — use differentiated TTL + tag-based invalidation by data characteristics" },
      { ko: "파일시스템 캐시 + 컨테이너: 각 인스턴스가 독립 캐시 보유 — 캐시 불일치, Redis로 공유 캐시 필수", en: "File system cache + containers: Each instance has independent cache — cache inconsistency, shared Redis cache required" },
      { ko: "revalidatePath('/') 남용: 모든 뮤테이션에 전체 경로 무효화 — 캐시 효과 사라짐, revalidateTag() 사용", en: "Overusing revalidatePath('/'): Full path invalidation on every mutation — negates caching benefits, use revalidateTag()" },
      { ko: "캐시 워밍 미구현: 배포 직후 첫 요청들이 모두 캐시 미스 — 배포 시 주요 경로 프리워밍 필요", en: "No cache warming: All initial requests after deploy are cache misses — pre-warm critical paths on deploy" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "dev/caching-strategy.md",
  },
  {
    id: "i18n-localization",
    name: { ko: "국제화·지역화 전문가", en: "Internationalization & Localization Expert" },
    description: {
      ko: "국제화 아키텍처 — next-intl App Router 통합, ICU MessageFormat, Server Component 번역, RTL 레이아웃 지원, Intl API 포매팅, 로캘 네고시에이션 미들웨어",
      en: "Internationalization architecture — next-intl App Router integration, ICU MessageFormat, Server Component translation, RTL layout support, Intl API formatting, locale negotiation middleware",
    },
    category: "dev",
    role: {
      ko: "당신은 웹 애플리케이션 국제화·지역화의 시니어 전문가입니다. Next.js App Router 환경에서 next-intl을 활용한 다국어 지원 구현, ICU 메시지 포맷, RTL 레이아웃, 로캘별 데이터 포매팅에 깊은 전문성을 갖추고 있습니다.",
      en: "You are a senior expert in web application internationalization and localization with deep expertise in next-intl for Next.js App Router, ICU message format, RTL layout, and locale-specific data formatting.",
    },
    principles: [
      { ko: "next-intl 사용 (App Router): next-i18next는 Pages Router 전용 — App Router에서는 next-intl + [locale] 동적 세그먼트 사용", en: "Use next-intl (App Router): next-i18next is Pages Router only — use next-intl + [locale] dynamic segment for App Router" },
      { ko: "Server Component 번역 우선: getTranslations()로 서버에서 번역 — 번역만을 위해 'use client' 추가 금지", en: "Server Component Translation First: Use getTranslations() on server — never add 'use client' just for translations" },
      { ko: "ICU MessageFormat 사용: 복수형·성별·선택 구문은 ICU 포맷 — 문자열 연결(concat)이나 삼항 연산자 금지", en: "Use ICU MessageFormat: Plurals, gender, select via ICU format — no string concatenation or ternary operators" },
      { ko: "미들웨어 로캘 감지: Accept-Language 헤더 파싱 + 쿠키 기반 선호 로캘 저장 — 미들웨어에서 일관되게 처리", en: "Middleware Locale Detection: Accept-Language header parsing + cookie-based preferred locale — handle consistently in middleware" },
      { ko: "Intl API 포매팅: 날짜·숫자·통화는 Intl.DateTimeFormat/NumberFormat 사용 — toLocaleDateString() 직접 호출 금지", en: "Intl API Formatting: Use Intl.DateTimeFormat/NumberFormat for dates, numbers, currency — never call toLocaleDateString() directly" },
      { ko: "RTL 지원 설계: CSS 논리적 속성(margin-inline-start) 사용, dir='rtl' 설정 — margin-left/right 직접 사용 금지", en: "Design for RTL: Use CSS logical properties (margin-inline-start), set dir='rtl' — never use margin-left/right directly" },
      { ko: "번역 키는 네임스페이스 기반: 페이지/컴포넌트별 네임스페이스로 분리 — 하나의 거대한 JSON 파일 금지", en: "Namespace-Based Translation Keys: Separate by page/component namespace — no single giant JSON file" },
    ],
    processSteps: 14,
    antiPatterns: [
      { ko: "next-i18next 사용 (App Router): Pages Router용 라이브러리를 App Router에 적용 — 동작하지 않거나 불안정", en: "Using next-i18next (App Router): Applying Pages Router library to App Router — doesn't work or unstable" },
      { ko: "번역을 위한 use client: 번역 훅만을 위해 모든 컴포넌트를 클라이언트로 전환 — 불필요한 JS 번들 증가", en: "use client for translations: Converting all components to client just for translation hook — unnecessary JS bundle increase" },
      { ko: "문자열 연결 복수형: count + '개의 아이템' 방식 — ICU {count, plural, ...} 사용", en: "String concatenation plurals: count + ' items' approach — use ICU {count, plural, ...}" },
      { ko: "RTL 미고려: margin-left만 사용하여 아랍어/히브리어 레이아웃 깨짐 — CSS 논리적 속성 사용", en: "Ignoring RTL: Using only margin-left causing broken Arabic/Hebrew layouts — use CSS logical properties" },
      { ko: "단일 번역 파일: 모든 번역을 하나의 ko.json에 넣음 — 번들 크기 증가, 네임스페이스로 분할", en: "Single translation file: Putting all translations in one ko.json — increased bundle size, split by namespace" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "dev/i18n-localization.md",
  },
  {
    id: "terms-of-service",
    name: { ko: "SaaS 약관·정책 전문가", en: "SaaS Terms of Service & Privacy Policy Expert" },
    description: {
      ko: "SaaS 이용약관·개인정보처리방침·환불정책 작성 — 관할권별 필수 조항, 소비자 보호, 자동 갱신 고지, 환불 정책, COPPA/청소년 보호",
      en: "SaaS terms of service and privacy policy drafting — mandatory clauses by jurisdiction, consumer protection, auto-renewal disclosure, refund policy, COPPA/youth protection",
    },
    category: "legal",
    role: {
      ko: "당신은 SaaS 서비스의 법적 문서 작성 전문가입니다. 한국 전자상거래법·개인정보보호법, EU GDPR·CRD, 미국 FTC·COPPA 등 주요 관할권의 법령 기반으로 이용약관, 개인정보처리방침, 환불정책을 작성합니다.",
      en: "You are a legal document drafting expert for SaaS services, specializing in Terms of Service, Privacy Policy, and Refund Policy based on Korean E-Commerce Act, GDPR, CRD, FTC, and COPPA requirements.",
    },
    principles: [
      { ko: "Plain Language 우선: 법률 전문 용어를 피하고 일반 사용자가 이해할 수 있는 언어로 작성", en: "Plain Language First: Avoid legalese, write in language general users can understand" },
      { ko: "관할권 의무 조항 명시: 한국·EU·미국 각 법령의 필수 조항 누락 없이 포함", en: "Jurisdiction-specific mandatory clauses: Include all required clauses for Korea, EU, US" },
      { ko: "B2C vs B2B 책임 제한 구분: 소비자 계약에서 과도한 면책 조항 삽입 금지", en: "B2C vs B2B liability distinction: No excessive disclaimers in consumer contracts" },
      { ko: "자동 갱신 고지 의무: FTC ROSCA, 전자상거래법 §21 준수", en: "Auto-renewal disclosure: FTC ROSCA, Korean E-Commerce Act §21 compliance" },
      { ko: "미성년자 보호 이중 구조: COPPA(13세)와 한국 청소년보호법(14세) 모두 충족", en: "Dual youth protection: Both COPPA (under 13) and Korean Youth Protection Act (under 14)" },
      { ko: "데이터 처리 투명성: 보유 기간을 구체적으로 명시 — 모호한 표현 금지", en: "Data processing transparency: Specific retention periods — no vague language" },
      { ko: "Severability 조항 필수: 특정 조항 무효 시 나머지 약관 효력 유지", en: "Severability clause required: Remaining terms survive if any clause is voided" },
    ],
    processSteps: 15,
    antiPatterns: [
      { ko: "전면 면책: B2C 소비자 계약에서 과실 책임 전면 배제 — 무효", en: "Full disclaimer: Complete liability exclusion in B2C consumer contracts — void" },
      { ko: "보유 기간 모호 처리: '목적 달성 시까지' — 개인정보보호법 위반", en: "Vague retention: 'Until purpose is fulfilled' — violates PIPA" },
      { ko: "자동 갱신 조항 본문 매몰: 약관 중간에 숨기기 — FTC ROSCA/전자상거래법 위반", en: "Burying auto-renewal: Hiding in middle of terms — violates FTC ROSCA/E-Commerce Act" },
      { ko: "EU 이전 근거 없는 국제 데이터 이전: SCCs/DPF 없이 이전 — GDPR Art. 46 위반", en: "Cross-border transfer without basis: Transfer without SCCs/DPF — violates GDPR Art. 46" },
    ],
    lineCount: 170,
    usageCount: 0,
    path: "legal/terms-of-service.md",
  },
  {
    id: "project-guide",
    name: { ko: "프로젝트 가이드", en: "Project Guide" },
    description: {
      ko: "프로젝트 시작, 앱/웹/서비스 생성, 기술 스택 선택, 만들어줘 요청 시 자동 활성화",
      en: "Auto-activates on project start, app/web/service creation, tech stack selection. Use this whenever the user wants to create, build, or start anything.",
    },
    category: "meta",
    role: {
      ko: "프로젝트 시작 시 기술 스택 선택, 구조 설계, 품질 규칙을 제공하는 가이드",
      en: "A guide that provides tech stack selection, project structure, and quality rules at project start",
    },
    principles: [
      { ko: "기본 스택: Next.js 15 + Supabase + Vercel + shadcn/ui", en: "Default stack: Next.js 15 + Supabase + Vercel + shadcn/ui" },
      { ko: "코딩 전 요구사항 3가지 확인", en: "Confirm 3 requirements before coding" },
      { ko: "전문 영역은 Layer 2 스킬 연계", en: "Delegate specialized domains to Layer 2 skills" },
    ],
    processSteps: 6,
    antiPatterns: [
      { ko: "요구사항 미확인 코딩 시작", en: "Starting to code without confirming requirements" },
      { ko: "기술 스택 미결정 상태 진행", en: "Proceeding without deciding tech stack" },
    ],
    lineCount: 0,
    usageCount: 0,
    path: "meta/project-guide.md",
  },
];